# Form implementation generated from reading ui file 'f:\Web Development\uiu-mariner\uiu-mariner-1\src\views\main_window.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1375, 936)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 720))
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: #1e1e1e;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("QWidget {\n"
"    background-color: #1e1e1e;\n"
"    color: #e0e0e0;\n"
"    font-family: \"Segoe UI\", Arial, sans-serif;\n"
"    font-size: 10pt;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.mainVerticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.mainVerticalLayout.setContentsMargins(8, 8, 8, 8)
        self.mainVerticalLayout.setSpacing(8)
        self.mainVerticalLayout.setObjectName("mainVerticalLayout")
        self.topToolbarLayout = QtWidgets.QHBoxLayout()
        self.topToolbarLayout.setObjectName("topToolbarLayout")
        self.lblLogo = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblLogo.setMinimumSize(QtCore.QSize(60, 60))
        self.lblLogo.setMaximumSize(QtCore.QSize(60, 60))
        self.lblLogo.setStyleSheet("/* Labels */\n"
"QLabel {\n"
"    color: #e0e0e0;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QLabel#lblStatus {\n"
"    padding: 4px 12px;\n"
"    border-radius: 4px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel[frameShape=\"4\"] { /* Box frame */\n"
"    background-color: #252526;\n"
"    border: 2px solid #3f3f46;\n"
"    border-radius: 4px;\n"
"}")
        self.lblLogo.setText("")
        self.lblLogo.setPixmap(QtGui.QPixmap("f:\\Web Development\\uiu-mariner\\uiu-mariner-1\\src\\views\\239255497-removebg-preview.png"))
        self.lblLogo.setScaledContents(True)
        self.lblLogo.setObjectName("lblLogo")
        self.topToolbarLayout.addWidget(self.lblLogo)
        self.lblAppTitle = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblAppTitle.setStyleSheet("/* Labels */\n"
"QLabel {\n"
"    color: #e0e0e0;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QLabel#lblStatus {\n"
"    padding: 4px 12px;\n"
"    border-radius: 4px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel[frameShape=\"4\"] { /* Box frame */\n"
"    background-color: #252526;\n"
"    border: 2px solid #3f3f46;\n"
"    border-radius: 4px;\n"
"}")
        self.lblAppTitle.setObjectName("lblAppTitle")
        self.topToolbarLayout.addWidget(self.lblAppTitle)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.topToolbarLayout.addItem(spacerItem)
        self.btnConnect = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnConnect.sizePolicy().hasHeightForWidth())
        self.btnConnect.setSizePolicy(sizePolicy)
        self.btnConnect.setMinimumSize(QtCore.QSize(130, 40))
        self.btnConnect.setStyleSheet("QPushButton {\n"
"    background-color: #0e639c;\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    padding: 8px 16px;\n"
"    border-radius: 4px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #1177bb;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #0d5a8f;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #3f3f46;\n"
"    color: #808080;\n"
"}\n"
"\n"
"QPushButton#btnEmergencyStop {\n"
"    background-color: #c42b1c;\n"
"}\n"
"\n"
"QPushButton#btnEmergencyStop:hover {\n"
"    background-color: #e03e2e;\n"
"}")
        self.btnConnect.setObjectName("btnConnect")
        self.topToolbarLayout.addWidget(self.btnConnect)
        self.btnDisconnect = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnDisconnect.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDisconnect.sizePolicy().hasHeightForWidth())
        self.btnDisconnect.setSizePolicy(sizePolicy)
        self.btnDisconnect.setMinimumSize(QtCore.QSize(130, 40))
        self.btnDisconnect.setStyleSheet("QPushButton {\n"
"    background-color: #0e639c;\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    padding: 8px 16px;\n"
"    border-radius: 4px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #1177bb;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #0d5a8f;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #3f3f46;\n"
"    color: #808080;\n"
"}\n"
"\n"
"QPushButton#btnEmergencyStop {\n"
"    background-color: #c42b1c;\n"
"}\n"
"\n"
"QPushButton#btnEmergencyStop:hover {\n"
"    background-color: #e03e2e;\n"
"}")
        self.btnDisconnect.setObjectName("btnDisconnect")
        self.topToolbarLayout.addWidget(self.btnDisconnect)
        self.line = QtWidgets.QFrame(parent=self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.topToolbarLayout.addWidget(self.line)
        self.btnConnectJoystick = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnConnectJoystick.sizePolicy().hasHeightForWidth())
        self.btnConnectJoystick.setSizePolicy(sizePolicy)
        self.btnConnectJoystick.setMinimumSize(QtCore.QSize(150, 40))
        self.btnConnectJoystick.setStyleSheet("QPushButton {\n"
"    background-color: #0e639c;\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    padding: 8px 16px;\n"
"    border-radius: 4px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #1177bb;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #0d5a8f;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #3f3f46;\n"
"    color: #808080;\n"
"}\n"
"\n"
"QPushButton#btnEmergencyStop {\n"
"    background-color: #c42b1c;\n"
"}\n"
"\n"
"QPushButton#btnEmergencyStop:hover {\n"
"    background-color: #e03e2e;\n"
"}")
        self.btnConnectJoystick.setObjectName("btnConnectJoystick")
        self.topToolbarLayout.addWidget(self.btnConnectJoystick)
        self.line_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.topToolbarLayout.addWidget(self.line_2)
        self.btnArm = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnArm.setEnabled(False)
        self.btnArm.setMinimumSize(QtCore.QSize(130, 40))
        self.btnArm.setStyleSheet("QPushButton {\n"
"    background-color: #0e639c;\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    padding: 8px 16px;\n"
"    border-radius: 4px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #1177bb;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #0d5a8f;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #3f3f46;\n"
"    color: #808080;\n"
"}\n"
"\n"
"QPushButton#btnEmergencyStop {\n"
"    background-color: #c42b1c;\n"
"}\n"
"\n"
"QPushButton#btnEmergencyStop:hover {\n"
"    background-color: #e03e2e;\n"
"}")
        self.btnArm.setObjectName("btnArm")
        self.topToolbarLayout.addWidget(self.btnArm)
        self.btnEmergencyStop = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnEmergencyStop.setMinimumSize(QtCore.QSize(170, 40))
        self.btnEmergencyStop.setStyleSheet("QPushButton {\n"
"    background-color: #0e639c;\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    padding: 8px 16px;\n"
"    border-radius: 4px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #1177bb;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #0d5a8f;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #3f3f46;\n"
"    color: #808080;\n"
"}\n"
"\n"
"QPushButton#btnEmergencyStop {\n"
"    background-color: #c42b1c;\n"
"}\n"
"\n"
"QPushButton#btnEmergencyStop:hover {\n"
"    background-color: #e03e2e;\n"
"}")
        self.btnEmergencyStop.setObjectName("btnEmergencyStop")
        self.topToolbarLayout.addWidget(self.btnEmergencyStop)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.topToolbarLayout.addItem(spacerItem1)
        self.lblConnectionStatus = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblConnectionStatus.setMinimumSize(QtCore.QSize(150, 40))
        self.lblConnectionStatus.setStyleSheet("/* Labels */\n"
"QLabel {\n"
"    color: #e0e0e0;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QLabel#lblStatus {\n"
"    padding: 4px 12px;\n"
"    border-radius: 4px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel[frameShape=\"4\"] { /* Box frame */\n"
"    background-color: #252526;\n"
"    border: 2px solid #3f3f46;\n"
"    border-radius: 4px;\n"
"}")
        self.lblConnectionStatus.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblConnectionStatus.setObjectName("lblConnectionStatus")
        self.topToolbarLayout.addWidget(self.lblConnectionStatus)
        self.lblBatteryStatus = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblBatteryStatus.setMinimumSize(QtCore.QSize(130, 40))
        self.lblBatteryStatus.setStyleSheet("/* Labels */\n"
"QLabel {\n"
"    color: #e0e0e0;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QLabel#lblStatus {\n"
"    padding: 4px 12px;\n"
"    border-radius: 4px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel[frameShape=\"4\"] { /* Box frame */\n"
"    background-color: #252526;\n"
"    border: 2px solid #3f3f46;\n"
"    border-radius: 4px;\n"
"}")
        self.lblBatteryStatus.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblBatteryStatus.setObjectName("lblBatteryStatus")
        self.topToolbarLayout.addWidget(self.lblBatteryStatus)
        self.mainVerticalLayout.addLayout(self.topToolbarLayout)
        self.mainContentLayout = QtWidgets.QHBoxLayout()
        self.mainContentLayout.setSpacing(12)
        self.mainContentLayout.setObjectName("mainContentLayout")
        self.leftPanelLayout = QtWidgets.QVBoxLayout()
        self.leftPanelLayout.setSpacing(8)
        self.leftPanelLayout.setObjectName("leftPanelLayout")
        self.grpCameraFeed = QtWidgets.QGroupBox(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpCameraFeed.sizePolicy().hasHeightForWidth())
        self.grpCameraFeed.setSizePolicy(sizePolicy)
        self.grpCameraFeed.setStyleSheet("QGroupBox {\n"
"    border: 2px solid #3f3f46;\n"
"    border-radius: 6px;\n"
"    margin-top: 12px;\n"
"    padding-top: 8px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left;\n"
"    padding: 0 8px;\n"
"    color: #0db3ff;\n"
"}")
        self.grpCameraFeed.setObjectName("grpCameraFeed")
        self.cameraLayout = QtWidgets.QVBoxLayout(self.grpCameraFeed)
        self.cameraLayout.setObjectName("cameraLayout")
        self.lblMainCamera = QtWidgets.QLabel(parent=self.grpCameraFeed)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblMainCamera.sizePolicy().hasHeightForWidth())
        self.lblMainCamera.setSizePolicy(sizePolicy)
        self.lblMainCamera.setMinimumSize(QtCore.QSize(640, 360))
        self.lblMainCamera.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.lblMainCamera.setScaledContents(False)
        self.lblMainCamera.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblMainCamera.setObjectName("lblMainCamera")
        self.cameraLayout.addWidget(self.lblMainCamera)
        self.cameraControlsLayout = QtWidgets.QHBoxLayout()
        self.cameraControlsLayout.setObjectName("cameraControlsLayout")
        self.btnRecord = QtWidgets.QPushButton(parent=self.grpCameraFeed)
        self.btnRecord.setStyleSheet("QPushButton {\n"
"    background-color: #0e639c;\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    padding: 8px 16px;\n"
"    border-radius: 4px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #1177bb;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #0d5a8f;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #3f3f46;\n"
"    color: #808080;\n"
"}\n"
"\n"
"QPushButton#btnEmergencyStop {\n"
"    background-color: #c42b1c;\n"
"}\n"
"\n"
"QPushButton#btnEmergencyStop:hover {\n"
"    background-color: #e03e2e;\n"
"}")
        self.btnRecord.setObjectName("btnRecord")
        self.cameraControlsLayout.addWidget(self.btnRecord)
        self.btnSnapshot = QtWidgets.QPushButton(parent=self.grpCameraFeed)
        self.btnSnapshot.setStyleSheet("QPushButton {\n"
"    background-color: #0e639c;\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    padding: 8px 16px;\n"
"    border-radius: 4px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #1177bb;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #0d5a8f;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #3f3f46;\n"
"    color: #808080;\n"
"}\n"
"\n"
"QPushButton#btnEmergencyStop {\n"
"    background-color: #c42b1c;\n"
"}\n"
"\n"
"QPushButton#btnEmergencyStop:hover {\n"
"    background-color: #e03e2e;\n"
"}")
        self.btnSnapshot.setObjectName("btnSnapshot")
        self.cameraControlsLayout.addWidget(self.btnSnapshot)
        self.cmbCameraSelect = QtWidgets.QComboBox(parent=self.grpCameraFeed)
        self.cmbCameraSelect.setStyleSheet("QComboBox {\n"
"    background-color: #252526;\n"
"    border: 2px solid #3f3f46;\n"
"    border-radius: 4px;\n"
"    padding: 4px 8px;\n"
"    color: #e0e0e0;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border-color: #0e639c;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border: none;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #2d2d30;\n"
"    border: 1px solid #3f3f46;\n"
"    selection-background-color: #0e639c;\n"
"}\n"
"")
        self.cmbCameraSelect.setObjectName("cmbCameraSelect")
        self.cmbCameraSelect.addItem("")
        self.cmbCameraSelect.addItem("")
        self.cameraControlsLayout.addWidget(self.cmbCameraSelect)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.cameraControlsLayout.addItem(spacerItem2)
        self.cameraLayout.addLayout(self.cameraControlsLayout)
        self.leftPanelLayout.addWidget(self.grpCameraFeed)
        self.secondaryCamerasLayout = QtWidgets.QHBoxLayout()
        self.secondaryCamerasLayout.setObjectName("secondaryCamerasLayout")
        self.lblCamera2 = QtWidgets.QLabel(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCamera2.sizePolicy().hasHeightForWidth())
        self.lblCamera2.setSizePolicy(sizePolicy)
        self.lblCamera2.setMinimumSize(QtCore.QSize(200, 120))
        self.lblCamera2.setStyleSheet("/* Labels */\n"
"QLabel {\n"
"    color: #e0e0e0;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QLabel#lblStatus {\n"
"    padding: 4px 12px;\n"
"    border-radius: 4px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel[frameShape=\"4\"] { /* Box frame */\n"
"    background-color: #252526;\n"
"    border: 2px solid #3f3f46;\n"
"    border-radius: 4px;\n"
"}")
        self.lblCamera2.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.lblCamera2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblCamera2.setObjectName("lblCamera2")
        self.secondaryCamerasLayout.addWidget(self.lblCamera2)
        self.lblCamera3 = QtWidgets.QLabel(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCamera3.sizePolicy().hasHeightForWidth())
        self.lblCamera3.setSizePolicy(sizePolicy)
        self.lblCamera3.setMinimumSize(QtCore.QSize(200, 120))
        self.lblCamera3.setStyleSheet("/* Labels */\n"
"QLabel {\n"
"    color: #e0e0e0;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QLabel#lblStatus {\n"
"    padding: 4px 12px;\n"
"    border-radius: 4px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel[frameShape=\"4\"] { /* Box frame */\n"
"    background-color: #252526;\n"
"    border: 2px solid #3f3f46;\n"
"    border-radius: 4px;\n"
"}")
        self.lblCamera3.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.lblCamera3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblCamera3.setObjectName("lblCamera3")
        self.secondaryCamerasLayout.addWidget(self.lblCamera3)
        self.lblCamera4 = QtWidgets.QLabel(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCamera4.sizePolicy().hasHeightForWidth())
        self.lblCamera4.setSizePolicy(sizePolicy)
        self.lblCamera4.setMinimumSize(QtCore.QSize(200, 120))
        self.lblCamera4.setStyleSheet("/* Labels */\n"
"QLabel {\n"
"    color: #e0e0e0;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QLabel#lblStatus {\n"
"    padding: 4px 12px;\n"
"    border-radius: 4px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel[frameShape=\"4\"] { /* Box frame */\n"
"    background-color: #252526;\n"
"    border: 2px solid #3f3f46;\n"
"    border-radius: 4px;\n"
"}")
        self.lblCamera4.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.lblCamera4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblCamera4.setObjectName("lblCamera4")
        self.secondaryCamerasLayout.addWidget(self.lblCamera4)
        self.leftPanelLayout.addLayout(self.secondaryCamerasLayout)
        self.mainContentLayout.addLayout(self.leftPanelLayout)
        self.rightPanelLayout = QtWidgets.QVBoxLayout()
        self.rightPanelLayout.setSpacing(8)
        self.rightPanelLayout.setObjectName("rightPanelLayout")
        self.grpTelemetry = QtWidgets.QGroupBox(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpTelemetry.sizePolicy().hasHeightForWidth())
        self.grpTelemetry.setSizePolicy(sizePolicy)
        self.grpTelemetry.setStyleSheet("QGroupBox {\n"
"    border: 2px solid #3f3f46;\n"
"    border-radius: 6px;\n"
"    margin-top: 12px;\n"
"    padding-top: 8px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left;\n"
"    padding: 0 8px;\n"
"    color: #0db3ff;\n"
"}")
        self.grpTelemetry.setObjectName("grpTelemetry")
        self.telemetryGrid = QtWidgets.QGridLayout(self.grpTelemetry)
        self.telemetryGrid.setObjectName("telemetryGrid")
        self.lblDepthTitle = QtWidgets.QLabel(parent=self.grpTelemetry)
        self.lblDepthTitle.setStyleSheet("/* Labels */\n"
"QLabel {\n"
"    color: #e0e0e0;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QLabel#lblStatus {\n"
"    padding: 4px 12px;\n"
"    border-radius: 4px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel[frameShape=\"4\"] { /* Box frame */\n"
"    background-color: #252526;\n"
"    border: 2px solid #3f3f46;\n"
"    border-radius: 4px;\n"
"}")
        self.lblDepthTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lblDepthTitle.setObjectName("lblDepthTitle")
        self.telemetryGrid.addWidget(self.lblDepthTitle, 0, 0, 1, 1)
        self.lcdDepth = QtWidgets.QLCDNumber(parent=self.grpTelemetry)
        self.lcdDepth.setMinimumSize(QtCore.QSize(120, 40))
        self.lcdDepth.setStyleSheet("QLCDNumber {\n"
"    background-color: #0a0a0a;\n"
"    border: 2px solid #3f3f46;\n"
"    border-radius: 4px;\n"
"}")
        self.lcdDepth.setDigitCount(6)
        self.lcdDepth.setObjectName("lcdDepth")
        self.telemetryGrid.addWidget(self.lcdDepth, 0, 1, 1, 1)
        self.lblDepthUnit = QtWidgets.QLabel(parent=self.grpTelemetry)
        self.lblDepthUnit.setStyleSheet("/* Labels */\n"
"QLabel {\n"
"    color: #e0e0e0;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QLabel#lblStatus {\n"
"    padding: 4px 12px;\n"
"    border-radius: 4px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel[frameShape=\"4\"] { /* Box frame */\n"
"    background-color: #252526;\n"
"    border: 2px solid #3f3f46;\n"
"    border-radius: 4px;\n"
"}")
        self.lblDepthUnit.setObjectName("lblDepthUnit")
        self.telemetryGrid.addWidget(self.lblDepthUnit, 0, 2, 1, 1)
        self.lblTempTitle = QtWidgets.QLabel(parent=self.grpTelemetry)
        self.lblTempTitle.setStyleSheet("/* Labels */\n"
"QLabel {\n"
"    color: #e0e0e0;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QLabel#lblStatus {\n"
"    padding: 4px 12px;\n"
"    border-radius: 4px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel[frameShape=\"4\"] { /* Box frame */\n"
"    background-color: #252526;\n"
"    border: 2px solid #3f3f46;\n"
"    border-radius: 4px;\n"
"}")
        self.lblTempTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lblTempTitle.setObjectName("lblTempTitle")
        self.telemetryGrid.addWidget(self.lblTempTitle, 1, 0, 1, 1)
        self.lcdTemp = QtWidgets.QLCDNumber(parent=self.grpTelemetry)
        self.lcdTemp.setMinimumSize(QtCore.QSize(120, 40))
        self.lcdTemp.setStyleSheet("QLCDNumber {\n"
"    background-color: #0a0a0a;\n"
"    border: 2px solid #3f3f46;\n"
"    border-radius: 4px;\n"
"}")
        self.lcdTemp.setDigitCount(5)
        self.lcdTemp.setObjectName("lcdTemp")
        self.telemetryGrid.addWidget(self.lcdTemp, 1, 1, 1, 1)
        self.lblTempUnit = QtWidgets.QLabel(parent=self.grpTelemetry)
        self.lblTempUnit.setStyleSheet("/* Labels */\n"
"QLabel {\n"
"    color: #e0e0e0;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QLabel#lblStatus {\n"
"    padding: 4px 12px;\n"
"    border-radius: 4px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel[frameShape=\"4\"] { /* Box frame */\n"
"    background-color: #252526;\n"
"    border: 2px solid #3f3f46;\n"
"    border-radius: 4px;\n"
"}")
        self.lblTempUnit.setObjectName("lblTempUnit")
        self.telemetryGrid.addWidget(self.lblTempUnit, 1, 2, 1, 1)
        self.lblHeadingTitle = QtWidgets.QLabel(parent=self.grpTelemetry)
        self.lblHeadingTitle.setStyleSheet("/* Labels */\n"
"QLabel {\n"
"    color: #e0e0e0;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QLabel#lblStatus {\n"
"    padding: 4px 12px;\n"
"    border-radius: 4px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel[frameShape=\"4\"] { /* Box frame */\n"
"    background-color: #252526;\n"
"    border: 2px solid #3f3f46;\n"
"    border-radius: 4px;\n"
"}")
        self.lblHeadingTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lblHeadingTitle.setObjectName("lblHeadingTitle")
        self.telemetryGrid.addWidget(self.lblHeadingTitle, 2, 0, 1, 1)
        self.lcdHeading = QtWidgets.QLCDNumber(parent=self.grpTelemetry)
        self.lcdHeading.setMinimumSize(QtCore.QSize(120, 40))
        self.lcdHeading.setStyleSheet("QLCDNumber {\n"
"    background-color: #0a0a0a;\n"
"    border: 2px solid #3f3f46;\n"
"    border-radius: 4px;\n"
"}")
        self.lcdHeading.setDigitCount(5)
        self.lcdHeading.setObjectName("lcdHeading")
        self.telemetryGrid.addWidget(self.lcdHeading, 2, 1, 1, 1)
        self.lblHeadingUnit = QtWidgets.QLabel(parent=self.grpTelemetry)
        self.lblHeadingUnit.setStyleSheet("/* Labels */\n"
"QLabel {\n"
"    color: #e0e0e0;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QLabel#lblStatus {\n"
"    padding: 4px 12px;\n"
"    border-radius: 4px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel[frameShape=\"4\"] { /* Box frame */\n"
"    background-color: #252526;\n"
"    border: 2px solid #3f3f46;\n"
"    border-radius: 4px;\n"
"}")
        self.lblHeadingUnit.setObjectName("lblHeadingUnit")
        self.telemetryGrid.addWidget(self.lblHeadingUnit, 2, 2, 1, 1)
        self.lblPressureTitle = QtWidgets.QLabel(parent=self.grpTelemetry)
        self.lblPressureTitle.setStyleSheet("/* Labels */\n"
"QLabel {\n"
"    color: #e0e0e0;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QLabel#lblStatus {\n"
"    padding: 4px 12px;\n"
"    border-radius: 4px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel[frameShape=\"4\"] { /* Box frame */\n"
"    background-color: #252526;\n"
"    border: 2px solid #3f3f46;\n"
"    border-radius: 4px;\n"
"}")
        self.lblPressureTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lblPressureTitle.setObjectName("lblPressureTitle")
        self.telemetryGrid.addWidget(self.lblPressureTitle, 3, 0, 1, 1)
        self.lcdPressure = QtWidgets.QLCDNumber(parent=self.grpTelemetry)
        self.lcdPressure.setMinimumSize(QtCore.QSize(120, 40))
        self.lcdPressure.setStyleSheet("QLCDNumber {\n"
"    background-color: #0a0a0a;\n"
"    border: 2px solid #3f3f46;\n"
"    border-radius: 4px;\n"
"}")
        self.lcdPressure.setDigitCount(6)
        self.lcdPressure.setObjectName("lcdPressure")
        self.telemetryGrid.addWidget(self.lcdPressure, 3, 1, 1, 1)
        self.lblPressureUnit = QtWidgets.QLabel(parent=self.grpTelemetry)
        self.lblPressureUnit.setStyleSheet("/* Labels */\n"
"QLabel {\n"
"    color: #e0e0e0;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QLabel#lblStatus {\n"
"    padding: 4px 12px;\n"
"    border-radius: 4px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel[frameShape=\"4\"] { /* Box frame */\n"
"    background-color: #252526;\n"
"    border: 2px solid #3f3f46;\n"
"    border-radius: 4px;\n"
"}")
        self.lblPressureUnit.setObjectName("lblPressureUnit")
        self.telemetryGrid.addWidget(self.lblPressureUnit, 3, 2, 1, 1)
        self.rightPanelLayout.addWidget(self.grpTelemetry)
        self.grpThrusters = QtWidgets.QGroupBox(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpThrusters.sizePolicy().hasHeightForWidth())
        self.grpThrusters.setSizePolicy(sizePolicy)
        self.grpThrusters.setStyleSheet("QGroupBox {\n"
"    border: 2px solid #3f3f46;\n"
"    border-radius: 6px;\n"
"    margin-top: 12px;\n"
"    padding-top: 8px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left;\n"
"    padding: 0 8px;\n"
"    color: #0db3ff;\n"
"}")
        self.grpThrusters.setObjectName("grpThrusters")
        self.thrustersLayout = QtWidgets.QVBoxLayout(self.grpThrusters)
        self.thrustersLayout.setObjectName("thrustersLayout")
        self.lblForwardThrust = QtWidgets.QLabel(parent=self.grpThrusters)
        self.lblForwardThrust.setStyleSheet("/* Labels */\n"
"QLabel {\n"
"    color: #e0e0e0;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QLabel#lblStatus {\n"
"    padding: 4px 12px;\n"
"    border-radius: 4px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel[frameShape=\"4\"] { /* Box frame */\n"
"    background-color: #252526;\n"
"    border: 2px solid #3f3f46;\n"
"    border-radius: 4px;\n"
"}")
        self.lblForwardThrust.setObjectName("lblForwardThrust")
        self.thrustersLayout.addWidget(self.lblForwardThrust)
        self.sliderForward = QtWidgets.QSlider(parent=self.grpThrusters)
        self.sliderForward.setStyleSheet("QSlider::groove:horizontal {\n"
"    height: 8px;\n"
"    background: #3f3f46;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: #0e639c;\n"
"    width: 18px;\n"
"    margin: -5px 0;\n"
"    border-radius: 9px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"    background: #1177bb;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"    background: #0e639c;\n"
"    border-radius: 4px;\n"
"}")
        self.sliderForward.setMinimum(-100)
        self.sliderForward.setMaximum(100)
        self.sliderForward.setProperty("value", 0)
        self.sliderForward.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.sliderForward.setTickPosition(QtWidgets.QSlider.TickPosition.TicksBelow)
        self.sliderForward.setTickInterval(25)
        self.sliderForward.setObjectName("sliderForward")
        self.thrustersLayout.addWidget(self.sliderForward)
        self.lblVerticalThrust = QtWidgets.QLabel(parent=self.grpThrusters)
        self.lblVerticalThrust.setStyleSheet("/* Labels */\n"
"QLabel {\n"
"    color: #e0e0e0;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QLabel#lblStatus {\n"
"    padding: 4px 12px;\n"
"    border-radius: 4px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel[frameShape=\"4\"] { /* Box frame */\n"
"    background-color: #252526;\n"
"    border: 2px solid #3f3f46;\n"
"    border-radius: 4px;\n"
"}")
        self.lblVerticalThrust.setObjectName("lblVerticalThrust")
        self.thrustersLayout.addWidget(self.lblVerticalThrust)
        self.sliderVertical = QtWidgets.QSlider(parent=self.grpThrusters)
        self.sliderVertical.setStyleSheet("QSlider::groove:horizontal {\n"
"    height: 8px;\n"
"    background: #3f3f46;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: #0e639c;\n"
"    width: 18px;\n"
"    margin: -5px 0;\n"
"    border-radius: 9px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"    background: #1177bb;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"    background: #0e639c;\n"
"    border-radius: 4px;\n"
"}")
        self.sliderVertical.setMinimum(-100)
        self.sliderVertical.setMaximum(100)
        self.sliderVertical.setProperty("value", 0)
        self.sliderVertical.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.sliderVertical.setTickPosition(QtWidgets.QSlider.TickPosition.TicksBelow)
        self.sliderVertical.setTickInterval(25)
        self.sliderVertical.setObjectName("sliderVertical")
        self.thrustersLayout.addWidget(self.sliderVertical)
        self.lblLateralThrust = QtWidgets.QLabel(parent=self.grpThrusters)
        self.lblLateralThrust.setStyleSheet("/* Labels */\n"
"QLabel {\n"
"    color: #e0e0e0;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QLabel#lblStatus {\n"
"    padding: 4px 12px;\n"
"    border-radius: 4px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel[frameShape=\"4\"] { /* Box frame */\n"
"    background-color: #252526;\n"
"    border: 2px solid #3f3f46;\n"
"    border-radius: 4px;\n"
"}")
        self.lblLateralThrust.setObjectName("lblLateralThrust")
        self.thrustersLayout.addWidget(self.lblLateralThrust)
        self.sliderLateral = QtWidgets.QSlider(parent=self.grpThrusters)
        self.sliderLateral.setStyleSheet("QSlider::groove:horizontal {\n"
"    height: 8px;\n"
"    background: #3f3f46;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: #0e639c;\n"
"    width: 18px;\n"
"    margin: -5px 0;\n"
"    border-radius: 9px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"    background: #1177bb;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"    background: #0e639c;\n"
"    border-radius: 4px;\n"
"}")
        self.sliderLateral.setMinimum(-100)
        self.sliderLateral.setMaximum(100)
        self.sliderLateral.setProperty("value", 0)
        self.sliderLateral.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.sliderLateral.setTickPosition(QtWidgets.QSlider.TickPosition.TicksBelow)
        self.sliderLateral.setTickInterval(25)
        self.sliderLateral.setObjectName("sliderLateral")
        self.thrustersLayout.addWidget(self.sliderLateral)
        self.rightPanelLayout.addWidget(self.grpThrusters)
        self.grpManipulator = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.grpManipulator.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpManipulator.sizePolicy().hasHeightForWidth())
        self.grpManipulator.setSizePolicy(sizePolicy)
        self.grpManipulator.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.grpManipulator.setObjectName("grpManipulator")
        self.manipulatorLayout = QtWidgets.QVBoxLayout(self.grpManipulator)
        self.manipulatorLayout.setObjectName("manipulatorLayout")
        self.gripperLayout = QtWidgets.QHBoxLayout()
        self.gripperLayout.setSpacing(5)
        self.gripperLayout.setObjectName("gripperLayout")
        self.btnOpenGripper = QtWidgets.QPushButton(parent=self.grpManipulator)
        self.btnOpenGripper.setStyleSheet("QPushButton {\n"
"    background-color: #0e639c;\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    padding: 8px 5px;\n"
"    border-radius: 4px;\n"
"    font-weight: bold;\n"
"    font-size:8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #1177bb;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #0d5a8f;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #3f3f46;\n"
"    color: #808080;\n"
"}\n"
"\n"
"QPushButton#btnEmergencyStop {\n"
"    background-color: #c42b1c;\n"
"}\n"
"\n"
"QPushButton#btnEmergencyStop:hover {\n"
"    background-color: #e03e2e;\n"
"}")
        self.btnOpenGripper.setIconSize(QtCore.QSize(20, 51))
        self.btnOpenGripper.setAutoDefault(False)
        self.btnOpenGripper.setObjectName("btnOpenGripper")
        self.gripperLayout.addWidget(self.btnOpenGripper)
        self.btnCloseGripper = QtWidgets.QPushButton(parent=self.grpManipulator)
        self.btnCloseGripper.setStyleSheet("QPushButton {\n"
"    background-color: #0e639c;\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    padding: 8px 5px;\n"
"    border-radius: 4px;\n"
"    font-weight: bold;\n"
"    font-size:8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #1177bb;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #0d5a8f;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #3f3f46;\n"
"    color: #808080;\n"
"}\n"
"\n"
"QPushButton#btnEmergencyStop {\n"
"    background-color: #c42b1c;\n"
"}\n"
"\n"
"QPushButton#btnEmergencyStop:hover {\n"
"    background-color: #e03e2e;\n"
"}")
        self.btnCloseGripper.setIconSize(QtCore.QSize(20, 51))
        self.btnCloseGripper.setObjectName("btnCloseGripper")
        self.gripperLayout.addWidget(self.btnCloseGripper)
        self.manipulatorLayout.addLayout(self.gripperLayout)
        self.lblGripperPosition = QtWidgets.QLabel(parent=self.grpManipulator)
        self.lblGripperPosition.setObjectName("lblGripperPosition")
        self.manipulatorLayout.addWidget(self.lblGripperPosition)
        self.progressGripper = QtWidgets.QProgressBar(parent=self.grpManipulator)
        self.progressGripper.setStyleSheet("QProgressBar {\n"
"    border: 2px solid #3f3f46;\n"
"    border-radius: 4px;\n"
"    text-align: center;\n"
"    background-color: #252526;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #0e639c;\n"
"    border-radius: 2px;\n"
"}")
        self.progressGripper.setProperty("value", 0)
        self.progressGripper.setObjectName("progressGripper")
        self.manipulatorLayout.addWidget(self.progressGripper)
        self.lblArmRotation = QtWidgets.QLabel(parent=self.grpManipulator)
        self.lblArmRotation.setObjectName("lblArmRotation")
        self.manipulatorLayout.addWidget(self.lblArmRotation)
        self.sliderArmRotation = QtWidgets.QSlider(parent=self.grpManipulator)
        self.sliderArmRotation.setStyleSheet("QSlider::groove:horizontal {\n"
"    height: 8px;\n"
"    background: #3f3f46;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: #0e639c;\n"
"    width: 18px;\n"
"    margin: -5px 0;\n"
"    border-radius: 9px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"    background: #1177bb;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"    background: #0e639c;\n"
"    border-radius: 4px;\n"
"}")
        self.sliderArmRotation.setMinimum(-180)
        self.sliderArmRotation.setMaximum(180)
        self.sliderArmRotation.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.sliderArmRotation.setTickPosition(QtWidgets.QSlider.TickPosition.TicksBelow)
        self.sliderArmRotation.setTickInterval(45)
        self.sliderArmRotation.setObjectName("sliderArmRotation")
        self.manipulatorLayout.addWidget(self.sliderArmRotation)
        self.rightPanelLayout.addWidget(self.grpManipulator)
        self.grpSensors = QtWidgets.QGroupBox(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpSensors.sizePolicy().hasHeightForWidth())
        self.grpSensors.setSizePolicy(sizePolicy)
        self.grpSensors.setObjectName("grpSensors")
        self.sensorsFormLayout = QtWidgets.QFormLayout(self.grpSensors)
        self.sensorsFormLayout.setObjectName("sensorsFormLayout")
        self.lblPitchTitle = QtWidgets.QLabel(parent=self.grpSensors)
        self.lblPitchTitle.setStyleSheet("/* Labels */\n"
"QLabel {\n"
"    color: #e0e0e0;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QLabel#lblStatus {\n"
"    padding: 4px 12px;\n"
"    border-radius: 4px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel[frameShape=\"4\"] { /* Box frame */\n"
"    background-color: #252526;\n"
"    border: 2px solid #3f3f46;\n"
"    border-radius: 4px;\n"
"}")
        self.lblPitchTitle.setObjectName("lblPitchTitle")
        self.sensorsFormLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblPitchTitle)
        self.lblPitch = QtWidgets.QLabel(parent=self.grpSensors)
        self.lblPitch.setStyleSheet("/* Labels */\n"
"QLabel {\n"
"    color: #e0e0e0;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QLabel#lblStatus {\n"
"    padding: 4px 12px;\n"
"    border-radius: 4px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel[frameShape=\"4\"] { /* Box frame */\n"
"    background-color: #252526;\n"
"    border: 2px solid #3f3f46;\n"
"    border-radius: 4px;\n"
"}")
        self.lblPitch.setObjectName("lblPitch")
        self.sensorsFormLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lblPitch)
        self.lblRollTitle = QtWidgets.QLabel(parent=self.grpSensors)
        self.lblRollTitle.setStyleSheet("/* Labels */\n"
"QLabel {\n"
"    color: #e0e0e0;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QLabel#lblStatus {\n"
"    padding: 4px 12px;\n"
"    border-radius: 4px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel[frameShape=\"4\"] { /* Box frame */\n"
"    background-color: #252526;\n"
"    border: 2px solid #3f3f46;\n"
"    border-radius: 4px;\n"
"}")
        self.lblRollTitle.setObjectName("lblRollTitle")
        self.sensorsFormLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblRollTitle)
        self.lblRoll = QtWidgets.QLabel(parent=self.grpSensors)
        self.lblRoll.setStyleSheet("/* Labels */\n"
"QLabel {\n"
"    color: #e0e0e0;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QLabel#lblStatus {\n"
"    padding: 4px 12px;\n"
"    border-radius: 4px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel[frameShape=\"4\"] { /* Box frame */\n"
"    background-color: #252526;\n"
"    border: 2px solid #3f3f46;\n"
"    border-radius: 4px;\n"
"}")
        self.lblRoll.setObjectName("lblRoll")
        self.sensorsFormLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lblRoll)
        self.lblVoltageTitle = QtWidgets.QLabel(parent=self.grpSensors)
        self.lblVoltageTitle.setStyleSheet("/* Labels */\n"
"QLabel {\n"
"    color: #e0e0e0;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QLabel#lblStatus {\n"
"    padding: 4px 12px;\n"
"    border-radius: 4px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel[frameShape=\"4\"] { /* Box frame */\n"
"    background-color: #252526;\n"
"    border: 2px solid #3f3f46;\n"
"    border-radius: 4px;\n"
"}")
        self.lblVoltageTitle.setObjectName("lblVoltageTitle")
        self.sensorsFormLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblVoltageTitle)
        self.lblVoltage = QtWidgets.QLabel(parent=self.grpSensors)
        self.lblVoltage.setStyleSheet("/* Labels */\n"
"QLabel {\n"
"    color: #e0e0e0;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QLabel#lblStatus {\n"
"    padding: 4px 12px;\n"
"    border-radius: 4px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel[frameShape=\"4\"] { /* Box frame */\n"
"    background-color: #252526;\n"
"    border: 2px solid #3f3f46;\n"
"    border-radius: 4px;\n"
"}")
        self.lblVoltage.setObjectName("lblVoltage")
        self.sensorsFormLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lblVoltage)
        self.lblCurrentTitle = QtWidgets.QLabel(parent=self.grpSensors)
        self.lblCurrentTitle.setStyleSheet("/* Labels */\n"
"QLabel {\n"
"    color: #e0e0e0;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QLabel#lblStatus {\n"
"    padding: 4px 12px;\n"
"    border-radius: 4px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel[frameShape=\"4\"] { /* Box frame */\n"
"    background-color: #252526;\n"
"    border: 2px solid #3f3f46;\n"
"    border-radius: 4px;\n"
"}")
        self.lblCurrentTitle.setObjectName("lblCurrentTitle")
        self.sensorsFormLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblCurrentTitle)
        self.lblCurrent = QtWidgets.QLabel(parent=self.grpSensors)
        self.lblCurrent.setStyleSheet("/* Labels */\n"
"QLabel {\n"
"    color: #e0e0e0;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QLabel#lblStatus {\n"
"    padding: 4px 12px;\n"
"    border-radius: 4px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel[frameShape=\"4\"] { /* Box frame */\n"
"    background-color: #252526;\n"
"    border: 2px solid #3f3f46;\n"
"    border-radius: 4px;\n"
"}")
        self.lblCurrent.setObjectName("lblCurrent")
        self.sensorsFormLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lblCurrent)
        self.rightPanelLayout.addWidget(self.grpSensors)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.rightPanelLayout.addItem(spacerItem3)
        self.mainContentLayout.addLayout(self.rightPanelLayout)
        self.mainVerticalLayout.addLayout(self.mainContentLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1375, 29))
        self.menubar.setStyleSheet("QMenuBar {\n"
"    background-color: #2d2d30;\n"
"    color: #e0e0e0;\n"
"    border-bottom: 1px solid #3f3f46;\n"
"}\n"
"\n"
"QMenuBar::item {\n"
"    background-color: transparent;\n"
"    padding: 4px 12px;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"    background-color: #3e3e42;\n"
"}")
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setStyleSheet("QMenu {\n"
"    background-color: #2d2d30;\n"
"    border: 1px solid #3f3f46;\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"    background-color: #094771;\n"
"}\n"
"")
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtWidgets.QMenu(parent=self.menubar)
        self.menuView.setStyleSheet("QMenu {\n"
"    background-color: #2d2d30;\n"
"    border: 1px solid #3f3f46;\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"    background-color: #094771;\n"
"}\n"
"")
        self.menuView.setObjectName("menuView")
        self.menuTools = QtWidgets.QMenu(parent=self.menubar)
        self.menuTools.setStyleSheet("QMenu {\n"
"    background-color: #2d2d30;\n"
"    border: 1px solid #3f3f46;\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"    background-color: #094771;\n"
"}\n"
"")
        self.menuTools.setObjectName("menuTools")
        self.menuHelp = QtWidgets.QMenu(parent=self.menubar)
        self.menuHelp.setStyleSheet("QMenu {\n"
"    background-color: #2d2d30;\n"
"    border: 1px solid #3f3f46;\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"    background-color: #094771;\n"
"}\n"
"")
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setStyleSheet("QStatusBar {\n"
"    background-color: #2d2d30;\n"
"    color: #e0e0e0;\n"
"    border-top: 1px solid #3f3f46;\n"
"}")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(parent=MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionNewSession = QtGui.QAction(parent=MainWindow)
        self.actionNewSession.setObjectName("actionNewSession")
        self.actionOpenLog = QtGui.QAction(parent=MainWindow)
        self.actionOpenLog.setObjectName("actionOpenLog")
        self.actionSettings = QtGui.QAction(parent=MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionFullscreen = QtGui.QAction(parent=MainWindow)
        self.actionFullscreen.setObjectName("actionFullscreen")
        self.actionResetLayout = QtGui.QAction(parent=MainWindow)
        self.actionResetLayout.setObjectName("actionResetLayout")
        self.actionCalibrateSensors = QtGui.QAction(parent=MainWindow)
        self.actionCalibrateSensors.setObjectName("actionCalibrateSensors")
        self.actionDiagnostics = QtGui.QAction(parent=MainWindow)
        self.actionDiagnostics.setObjectName("actionDiagnostics")
        self.actionUserManual = QtGui.QAction(parent=MainWindow)
        self.actionUserManual.setObjectName("actionUserManual")
        self.actionAbout = QtGui.QAction(parent=MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionNewSession)
        self.menuFile.addAction(self.actionOpenLog)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSettings)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuView.addAction(self.actionFullscreen)
        self.menuView.addAction(self.actionResetLayout)
        self.menuTools.addAction(self.actionCalibrateSensors)
        self.menuTools.addAction(self.actionDiagnostics)
        self.menuHelp.addAction(self.actionUserManual)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Mariner - Underwater ROV Control System"))
        self.lblAppTitle.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600; color:#ea8a35;\">UIU<br/>MARINER</span></p></body></html>"))
        self.btnConnect.setText(_translate("MainWindow", "🔌 Connect ROV"))
        self.btnDisconnect.setText(_translate("MainWindow", "⚡ Disconnect"))
        self.btnConnectJoystick.setToolTip(_translate("MainWindow", "Connect gamepad/joystick for manual control"))
        self.btnConnectJoystick.setText(_translate("MainWindow", "🎮 Connect Joystick"))
        self.btnArm.setText(_translate("MainWindow", "🛡️ Arm System"))
        self.btnEmergencyStop.setText(_translate("MainWindow", "🛑 EMERGENCY STOP"))
        self.lblConnectionStatus.setText(_translate("MainWindow", "⚫ Disconnected"))
        self.lblBatteryStatus.setText(_translate("MainWindow", "🔋 Battery: --%"))
        self.grpCameraFeed.setTitle(_translate("MainWindow", "📹 Primary Camera Feed"))
        self.lblMainCamera.setText(_translate("MainWindow", "No Video Signal"))
        self.btnRecord.setText(_translate("MainWindow", "⏺️ Record"))
        self.btnSnapshot.setText(_translate("MainWindow", "📷 Snapshot"))
        self.cmbCameraSelect.setItemText(0, _translate("MainWindow", "Front Camera"))
        self.cmbCameraSelect.setItemText(1, _translate("MainWindow", "Bottom Camera"))
        self.lblCamera2.setText(_translate("MainWindow", "Camera 2"))
        self.lblCamera3.setText(_translate("MainWindow", "Camera 3"))
        self.lblCamera4.setText(_translate("MainWindow", "Camera 4"))
        self.grpTelemetry.setTitle(_translate("MainWindow", "📊 Telemetry Data"))
        self.lblDepthTitle.setText(_translate("MainWindow", "Depth:"))
        self.lblDepthUnit.setText(_translate("MainWindow", "m"))
        self.lblTempTitle.setText(_translate("MainWindow", "Temperature:"))
        self.lblTempUnit.setText(_translate("MainWindow", "°C"))
        self.lblHeadingTitle.setText(_translate("MainWindow", "Heading:"))
        self.lblHeadingUnit.setText(_translate("MainWindow", "°"))
        self.lblPressureTitle.setText(_translate("MainWindow", "Pressure:"))
        self.lblPressureUnit.setText(_translate("MainWindow", "bar"))
        self.grpThrusters.setTitle(_translate("MainWindow", "🚀 Thruster Control"))
        self.lblForwardThrust.setText(_translate("MainWindow", "Forward/Reverse Power: 0%"))
        self.lblVerticalThrust.setText(_translate("MainWindow", "Vertical Power: 0%"))
        self.lblLateralThrust.setText(_translate("MainWindow", "Lateral Power: 0%"))
        self.grpManipulator.setTitle(_translate("MainWindow", "🦾  Arm"))
        self.btnOpenGripper.setText(_translate("MainWindow", "Open Gripper"))
        self.btnCloseGripper.setText(_translate("MainWindow", "Close Gripper"))
        self.lblGripperPosition.setText(_translate("MainWindow", "Gripper Position: 0%"))
        self.lblArmRotation.setText(_translate("MainWindow", "Arm Rotation: 0°"))
        self.grpSensors.setTitle(_translate("MainWindow", "📡 Sensor Readings"))
        self.lblPitchTitle.setText(_translate("MainWindow", "Pitch:"))
        self.lblPitch.setText(_translate("MainWindow", "0.0°"))
        self.lblRollTitle.setText(_translate("MainWindow", "Roll:"))
        self.lblRoll.setText(_translate("MainWindow", "0.0°"))
        self.lblVoltageTitle.setText(_translate("MainWindow", "Voltage:"))
        self.lblVoltage.setText(_translate("MainWindow", "0.0 V"))
        self.lblCurrentTitle.setText(_translate("MainWindow", "Current:"))
        self.lblCurrent.setText(_translate("MainWindow", "0.0 A"))
        self.menuFile.setTitle(_translate("MainWindow", "&File"))
        self.menuView.setTitle(_translate("MainWindow", "&View"))
        self.menuTools.setTitle(_translate("MainWindow", "&Tools"))
        self.menuHelp.setTitle(_translate("MainWindow", "&Help"))
        self.actionExit.setText(_translate("MainWindow", "E&xit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionNewSession.setText(_translate("MainWindow", "&New Session"))
        self.actionNewSession.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionOpenLog.setText(_translate("MainWindow", "&Open Log"))
        self.actionOpenLog.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSettings.setText(_translate("MainWindow", "&Settings"))
        self.actionSettings.setShortcut(_translate("MainWindow", "Ctrl+,"))
        self.actionFullscreen.setText(_translate("MainWindow", "&Fullscreen"))
        self.actionFullscreen.setShortcut(_translate("MainWindow", "F11"))
        self.actionResetLayout.setText(_translate("MainWindow", "&Reset Layout"))
        self.actionCalibrateSensors.setText(_translate("MainWindow", "&Calibrate Sensors"))
        self.actionDiagnostics.setText(_translate("MainWindow", "&Diagnostics"))
        self.actionUserManual.setText(_translate("MainWindow", "&User Manual"))
        self.actionUserManual.setShortcut(_translate("MainWindow", "F1"))
        self.actionAbout.setText(_translate("MainWindow", "&About"))
